### ISSUE TITLE
RSS output is poorly formatted in Feedly

### ISSUE THREAD

**Issue by zbentley** [TheKevJames/thekev.in#12]
Since you seemed like an interesting developer from our interactions re: puppet-homebrew, I followed your blog via Feedly. When doing so, I discovered that your RSS content has formatting issues (for me, at least). It shows up with weird artifacts and no content or teaser text, e.g. `[CDATA[ Allen. ]]`. 

See attached screenshot for example.
![feedly](https://cloud.githubusercontent.com/assets/10999109/17989691/46bc1132-6afd-11e6-89ba-ec8f177f796d.jpg)

**Comment by TheKevJames** [comment]
Thanks for the follow!

That screenshot it... odd. My rss feed is pretty slapped together, so I know there shouldn't be a _real_ description, but my feedly shows the title in the description rather than that CDATA mess. I wonder why it's different for us?

I'll look into this further, but just a quick question to narrow down where to look: do you have any modifications to your feedly or browser that may affect this? Themes, plugins, anything like that?

**Comment by TheKevJames** [comment]
Note to self: see [barteNERDS](http://www.bartenerds.com/rss.xml). Looks like they explicitly do some CDATA stuff in the description field.

**Comment by zbentley** [comment]
Nope, no plugins or customizations; I think that the only setting I've changed is display item size. It's still weird in incognito and firefox (no plugins, 100% stock). Not a major issue, obv.

**Comment by TheKevJames** [comment]
456328bb46ac introduces CDATA in description field, switches to using post body as the description instead of the title. Leaving this issue open until feedly refreshes and I can prove it worked.

**Comment by TheKevJames** [comment]
Looks good in my inoreader. Feedly doesn't look better for old posts -- this might be because [feedly doesn't update old posts](https://feedly.uservoice.com/forums/192636-suggestions/suggestions/3764215-feedly-does-not-appear-to-refresh-a-post-if-the-au), but I'm not actually sure that's the case.

Will close this next time I get around to writing a post if it looks good on feedly.

**Comment by TheKevJames** [comment]
Wow, I don't write blog posts very often. Closing since [my latest post](http://thekev.in/blog/2016-11-18-python-in-docker/) looked good to me.
